GET https://syntax-craftsman-9012.onrender.com/product

###
POST https://syntax-craftsman-9012.onrender.com/product
Content-Type: application/json

{
    "image": "https://www.bigbasket.com/media/uploads/p/m/40119406_5-fresho-coconut-chunks-single-serve.jpg?tr=w-3840,q=80",
    "discount": 62,
    "brand": "Fresho",
    "title": "Coconut Chunks - Single Serve New",
    "quantity": "80 g",
    "price": 21,
    "original_price": 55,
    "category": "Cut Fruit, Tender Coconut",
    "sub_category": "Cuts & Sprouts",
    "main_category": "Fruits & Vegetables"
  }